# Generated by Django 4.2.3 on 2026-06-24 02:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConnectFourGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_ai_game', models.BooleanField(default=False)),
                ('board', models.CharField(default='000000000000000000000000000000000000000000', max_length=42)),
                ('current_turn', models.IntegerField(default=1)),
                ('winner', models.IntegerField(blank=True, null=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('player_one', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='c4_games_as_one', to=settings.AUTH_USER_MODEL)),
                ('player_two', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='c4_games_as_two', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
