# Generated by Django 5.1 on 2025-05-31 19:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0002_conversation_directmessage_conversation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="directmessage",
            name="conversation",
            field=models.ForeignKey(
                help_text="The conversation this message belongs to",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="messages",
                to="chat.conversation",
            ),
        ),
    ]
