# Generated by Django 5.1 on 2026-02-08 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0003_alter_directmessage_conversation"),
    ]

    operations = [
        migrations.AddField(
            model_name="conversation",
            name="user1_deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="conversation",
            name="user2_deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
