# Generated by Django 5.1 on 2026-02-09 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0004_conversation_user1_deleted_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="conversation",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                help_text="Timestamp when the conversation was first created.",
            ),
        ),
    ]
