# Generated by Django 5.1 on 2025-05-18 14:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TicTacToeGame",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_ai_game",
                    models.BooleanField(
                        default=False,
                        help_text="Indicates if the game is played against an AI opponent. Set to True for AI games and False for multiplayer games.",
                    ),
                ),
                (
                    "board_state",
                    models.CharField(
                        default="_________",
                        help_text="Represents the current state of the 3x3 grid using '_' for empty spots.",
                        max_length=9,
                    ),
                ),
                (
                    "current_turn",
                    models.CharField(
                        default="X",
                        help_text="Tracks whose turn it is, either 'X' or 'O'.",
                        max_length=1,
                    ),
                ),
                (
                    "winner",
                    models.CharField(
                        blank=True,
                        help_text="Stores the winner of the game: 'X', 'O', or 'D' for draw.",
                        max_length=1,
                        null=True,
                    ),
                ),
                (
                    "is_completed",
                    models.BooleanField(
                        default=False,
                        help_text="Indicates wheather the game has been completed.",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="The time the game was created."
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="The last time the game was updated."
                    ),
                ),
                (
                    "player_o",
                    models.ForeignKey(
                        blank=True,
                        help_text="Player O can either be an AI or a second human player. If not provided, the game waits for a second player to join.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="player_o_games",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "player_x",
                    models.ForeignKey(
                        help_text="The user who created the game is automatically assigned as Player X.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="player_x_games",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
