# Generated by Django 5.1 on 2024-10-03 01:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="tictactoegame",
            name="player_o",
            field=models.ForeignKey(
                blank=True,
                help_text="Player O can either be an AI or a second human player. If not provided, the game waits for a second player to join.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="player_o_games",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="tictactoegame",
            name="player_x",
            field=models.ForeignKey(
                help_text="The user who created the game is automatically assigned as Player X.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="player_x_games",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
