# Generated by Django 5.1 on 2024-10-14 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0002_alter_tictactoegame_player_o_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="tictactoegame",
            name="is_ai_game",
            field=models.BooleanField(
                default=False,
                help_text="Indicates if the game is played against an AI opponent. Set to True for AI games and False for multiplayer games.",
            ),
        ),
    ]
