# Generated by Django 5.1 on 2024-12-14 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0003_tictactoegame_is_ai_game"),
    ]

    operations = [
        migrations.AddField(
            model_name="tictactoegame",
            name="is_completed",
            field=models.BooleanField(
                default=False,
                help_text="Indicates wheather the game has been completed.",
            ),
        ),
    ]
