# Generated by Django 5.1 on 2025-05-11 23:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Friendship",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_accepted",
                    models.BooleanField(
                        default=False,
                        help_text="Indicates whether the friend request has been accepted.",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Timestamp when the friend request was created.",
                    ),
                ),
                (
                    "from_user",
                    models.ForeignKey(
                        help_text="User who sent the friend request.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sent_friend_request",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "to_user",
                    models.ForeignKey(
                        help_text="User who received the friend request.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="received_friend_request",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Friendship",
                "verbose_name_plural": "Friendships",
                "db_table": "users_friendship",
                "ordering": ["-created_at"],
                "unique_together": {("from_user", "to_user")},
            },
        ),
    ]
