# Generated by Django 5.1 on 2026-07-28 14:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PokerGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_ai_game', models.BooleanField(default=False)),
                ('deck', models.JSONField(default=list)),
                ('community_cards', models.JSONField(default=list)),
                ('player_one_cards', models.JSONField(default=list)),
                ('player_two_cards', models.JSONField(default=list)),
                ('player_one_chips', models.IntegerField(default=1000)),
                ('player_two_chips', models.IntegerField(default=1000)),
                ('pot', models.IntegerField(default=0)),
                ('current_bet', models.IntegerField(default=0)),
                ('player_one_bet', models.IntegerField(default=0)),
                ('player_two_bet', models.IntegerField(default=0)),
                ('current_turn', models.IntegerField(default=1)),
                ('dealer', models.IntegerField(default=1)),
                ('phase', models.CharField(default='preflop', max_length=16)),
                ('last_action', models.CharField(blank=True, default='', max_length=64)),
                ('actions_since_raise', models.IntegerField(default=0)),
                ('winner', models.IntegerField(blank=True, null=True)),
                ('winning_label', models.CharField(blank=True, default='', max_length=64)),
                ('is_completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('player_one', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='poker_games_as_one', to=settings.AUTH_USER_MODEL)),
                ('player_two', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='poker_games_as_two', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
