# Generated by Django 5.1 on 2026-07-28 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokergame',
            name='hand_number',
            field=models.IntegerField(default=1),
        ),
    ]
