# Generated by Django 5.1 on 2026-07-28 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poker', '0002_pokergame_hand_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokergame',
            name='table_seats',
            field=models.JSONField(default=list),
        ),
    ]
