# Generated by Codex on 2026-07-28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("poker", "0003_pokergame_table_seats"),
    ]

    operations = [
        migrations.AddField(
            model_name="pokergame",
            name="starting_chips",
            field=models.IntegerField(default=1000),
        ),
        migrations.AddField(
            model_name="pokergame",
            name="small_blind",
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name="pokergame",
            name="big_blind",
            field=models.IntegerField(default=20),
        ),
        migrations.AddField(
            model_name="pokergame",
            name="turn_timer_seconds",
            field=models.IntegerField(default=45),
        ),
        migrations.AddField(
            model_name="pokergame",
            name="max_players",
            field=models.IntegerField(default=6),
        ),
    ]
