# Generated by Codex on 2026-07-28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("poker", "0004_pokergame_table_settings"),
    ]

    operations = [
        migrations.AddField(
            model_name="pokergame",
            name="current_turn_started_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
