# Generated by Codex on 2026-07-28

from django.db import migrations, models


def update_unstarted_tables(apps, schema_editor):
    PokerGame = apps.get_model("poker", "PokerGame")
    PokerGame.objects.filter(
        max_players=6,
        table_seats=[],
        player_one_cards=[],
        player_two_cards=[],
    ).update(max_players=9)


class Migration(migrations.Migration):

    dependencies = [
        ("poker", "0005_pokergame_current_turn_started_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pokergame",
            name="max_players",
            field=models.IntegerField(default=9),
        ),
        migrations.RunPython(update_unstarted_tables, migrations.RunPython.noop),
    ]
