# Generated by Django 5.1 on 2026-07-31 13:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poker', '0006_pokergame_max_players_nine'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PokerTournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80)),
                ('scheduled_start', models.DateTimeField()),
                ('max_players', models.IntegerField(default=6)),
                ('starting_chips', models.IntegerField(default=1000)),
                ('small_blind', models.IntegerField(default=10)),
                ('big_blind', models.IntegerField(default=20)),
                ('turn_timer_seconds', models.IntegerField(default=45)),
                ('status', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed'), ('in_progress', 'In progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='open', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_poker_tournaments', to=settings.AUTH_USER_MODEL)),
                ('game', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tournaments', to='poker.pokergame')),
            ],
            options={
                'ordering': ['scheduled_start', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PokerTournamentRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('registered', 'Registered'), ('withdrawn', 'Withdrawn'), ('removed', 'Removed')], default='registered', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='poker.pokertournament')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='poker_tournament_registrations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at', 'id'],
                'unique_together': {('tournament', 'user')},
            },
        ),
    ]
