# Generated by Django 5.1 on 2024-09-17 16:46

import django.utils.timezone
import users.image_path
import users.image_validators
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        help_text="Enter your email address. Used for login.",
                        max_length=254,
                        unique=True,
                        verbose_name="email address",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        help_text="Enter your first name.",
                        max_length=26,
                        verbose_name="First Name",
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        help_text="Enter your last name.",
                        max_length=26,
                        verbose_name="Last Name",
                    ),
                ),
                (
                    "avatar",
                    models.ImageField(
                        blank=True,
                        default=users.image_path.default_avatar,
                        help_text="Upload a profile picture to represent you in the game.",
                        null=True,
                        upload_to=users.image_path.avatar_upload_path,
                        validators=[
                            users.image_validators.validate_icon_image_size,
                            users.image_validators.validate_image_file_extension,
                        ],
                    ),
                ),
                (
                    "total_games_played",
                    models.IntegerField(
                        default=0,
                        help_text="The total number of games played by the user.",
                    ),
                ),
                (
                    "wins",
                    models.IntegerField(
                        default=0,
                        help_text="The total number of games won by the user.",
                    ),
                ),
                (
                    "losses",
                    models.IntegerField(
                        default=0,
                        help_text="The total number of games lost by the user.",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        default="offline",
                        help_text="Indicates whether the user is online or offline.",
                        max_length=10,
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "user",
                "verbose_name_plural": "users",
                "abstract": False,
            },
        ),
    ]
