# Generated by Django 5.1 on 2024-09-30 15:04

import users.image_path
import users.image_validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="avatar",
            field=models.ImageField(
                blank=True,
                default=users.image_path.default_avatar,
                help_text="Upload a profile picture to represent you in the game.",
                null=True,
                upload_to=users.image_path.avatar_upload_path,
                validators=[users.image_validators.validate_image_file_extension],
            ),
        ),
    ]
