# Generated by Django 5.1 on 2025-05-05 15:51

import django.db.models.deletion
import users.image_path
import users.image_validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_customuser_avatar"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="avatar",
            field=models.ImageField(
                blank=True,
                default=users.image_path.default_avatar,
                help_text="Upload a profile image. Default will be used if none is provided.",
                null=True,
                upload_to=users.image_path.avatar_upload_path,
                validators=[users.image_validators.validate_image_file_extension],
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="email",
            field=models.EmailField(
                help_text="Your login email address.",
                max_length=254,
                unique=True,
                verbose_name="email address",
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="first_name",
            field=models.CharField(
                help_text="Your first name.", max_length=26, verbose_name="First Name"
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="last_name",
            field=models.CharField(
                help_text="Your last name.", max_length=26, verbose_name="Last Name"
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="losses",
            field=models.IntegerField(
                default=0, help_text="Total number of games this user has lost."
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="status",
            field=models.CharField(
                default="offline",
                help_text='Current online status of the user (e.g., "online", "offline").',
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="total_games_played",
            field=models.IntegerField(
                default=0, help_text="Total number of games this user has played."
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="wins",
            field=models.IntegerField(
                default=0, help_text="Total number of games this user has won."
            ),
        ),
        migrations.CreateModel(
            name="Friendship",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_accepted",
                    models.BooleanField(
                        default=False,
                        help_text="Indicates whether the friend request has been accepted.",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Timestamp when the friend request was created.",
                    ),
                ),
                (
                    "from_user",
                    models.ForeignKey(
                        help_text="User who sent the friend request.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sent_friend_request",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "to_user",
                    models.ForeignKey(
                        help_text="User who received the friend request.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="received_friend_request",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Friendship",
                "verbose_name_plural": "Friendships",
                "ordering": ["-created_at"],
                "unique_together": {("from_user", "to_user")},
            },
        ),
    ]
