# Generated by Django 5.1 on 2025-05-18 04:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_alter_customuser_avatar_alter_customuser_email_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Friendship",
        ),
    ]
